### ISSUE TITLE
Find migratory bird dataset

### ISSUE THREAD

**Issue by rikkuness** [rikkuness/Introvertebrates#32]

**Comment by BMG1010** [comment]
Source:
Winkler DW, Gandoy FA, Areta JI, Iliff MJ, Rakhimberdiev E, Kardynal KJ, Hobson KA (2017) Long-distance range expansion and rapid adjustment of migration in a newly established population of Barn Swallows breeding in Argentina. Current Biology 27: 1–5. doi:10.1016/j.cub.2017.03.006

**Comment by rikkuness** [comment]
We have a dataset, it's not ideal but it works.
