### ISSUE TITLE
Use location from GPS etc. to center map

### ISSUE THREAD

**Issue by rikkuness** [rikkuness/Introvertebrates#76]
The page it's like "Near Me" but still defaults to South America, should be easy enough to take location coords now and put them into the `this.center` binding

**Comment by cadnce** [comment]
Fortuantely some wizard already worked out how to get coordinates in this
app!

**Comment by stevenjfr** [comment]
I think I just solved this :o

**Comment by stevenjfr** [comment]
stuck this in pan-to-location branch
